#DATE: <2019-06-15 Sat>
* TARGET
        华师
* PRINCIPLE
        坚持高效复习
P.S. 
1. 目标方向最重要，选一个你最想去的大学(去了解一些，然后相信自己选的一定是对的，并且是最好的)
2. 复习时间可以短些，但是一定要有效率，不要内耗，千万不要内耗，不要自己感动自己
3. 作息时间要调整好，睡眠要足够，有精神了才能有效率的学习，有午睡习惯那就坚持
4. 身体要保重好，该吃吃该喝喝，(趴在桌之上午睡的时候要盖件衣服，图书馆空调制冷不均衡，小心感冒)
5. 复习的方向要依照报考大学的考纲，统考的课程(e.g. 数学，市场上有复习用书，好好用，看看历年考题是怎么变的，
   有哪些题型，千万不要闭门造车), 英语的历年真题要早点做，得阅读，得英语, 你会发现阅读比你想的难，所以你要
   弄懂每个选项，看看陷阱是怎么设的，还有要小心翻译；徐涛的考研政治课不错，肖秀荣的 1000 题，你要做几遍，做熟，
   至于政治大题，基本背肖四就可以了，不用急；专业课，要看你自己。
6. 大头是数学和专业课，你要每天花足够的时间(数学很重要)
7. 所以你要做的是: 踏实复习, 大胆去考
   (我看过女神学习，觉得女神看书很认真的，所以你这段时间其他可以先放放，把考研放在第一位就可以了.
   你要知道自己是很厉害的，其他大部分都是臭鱼烂虾，当炮灰的；我从来觉得，我复习了多少，我就考多少，
   我不相信我有那么好运能够超常发挥，所以考试的时候太紧张了考差了都是借口，因为我能考多少我有底，所以我不虚，
   自然也不紧张，大胆考就是了)
8. 觉得累，就休息一下，不要疲劳战，学的稍微轻松一点.

Q. & A.
1. 关于考研是信息战，信息不对称
   是信息战，信息也的确不对称(至少人家二战的肯定比你知道的多是吧), 所以你尝试网上找一些信息(例如知乎),如果可以
   那就找以前的学长学姐问一下，但是这种信息影响没那么大，不要本末倒置，踏实认真复习才是最关键的!
2. 复习到后来觉得沮丧压抑难熬，心态都有点崩溃了怎么办?
   正常，大家都半斤八两，你受不了，我也受不了，这时候疲兵对疲兵，需要一点坚持，坚持不下去怎么办，出去走走，跑个步也行
   学会调整心态就行，但是不要让这种状态保持太久.

(Math : 140+
 English : 80+
 Politics : 75+
 Professional Course: 130+)

BEST WITHES!
